global:
  prefix: graphite
  interval: 1m
  from: -1min
  until: now
  timeout: 10

metrics:
  - metric: stats.example.*.*.user
    name: user_cnt
    doc: user cnt
    labels:
      service: ${3}
      app: ${2}
      project: ${1}

  - metric: stats.example.*.*.dau
    name: service-dau
    doc: service-dau
    labels:
      service_project: ${3}-${1}
      app: ${2}
      project: ${1}

  - metric: aliasByMetric(stats.example.*.*.dau)  # graphite return metric name: dau
    name: dau
    doc: dau
    labels:
      metric: ${0}
