global:
  prefix: graphite
  interval: 1m
  from: -1min
  until: now

metrics:
  - metric: example.*.*.user
    name: user_cnt
    doc: user cnt
    labels:
      app: ${1}
      project: ${2}

  - metric: example.*.*.dau
    name: dau
    doc: dau
    labels:
      app: ${1}
      project: ${2}
